name: repo_activity
version: "1.0.0"
config-version: 2

profile: repo_activity

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  repo_activity:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
